// Phase 10 (A3) — emoji catalogue for the category / savings-goal picker.
//
// Deliberately a plain data module with NO dependency: emoji-mart and friends
// are 150-300KB and bring their own styling to fight with. This file is loaded
// through a dynamic import() from EmojiPicker, so it stays out of the main
// bundle until someone actually opens the picker.
//
// Emoji render in the VIEWER's font, so on Alex's iPhone these are exactly the
// iOS glyphs he expects — nothing here ships an image set.
//
// Shape is [glyph, 'space separated search keywords']. Keywords are lowercase
// and deliberately terse; the glyph's obvious name is always included.
//
// Coverage is broad but not the entire 3,700-emoji Unicode set — skin-tone
// variants, family permutations and the long tail of flags are reachable
// through the picker's "paste any emoji" field instead (on a phone that's the
// emoji keyboard, which is how Alex will actually use it).

export const EMOJI_GROUPS = [
  {
    key: 'smileys',
    label: 'Smileys',
    tabIcon: '😀',
    items: [
      ['😀', 'grin happy smile face'], ['😃', 'smiley happy joy'], ['😄', 'smile happy laugh'],
      ['😁', 'beam grin happy'], ['😆', 'laugh squint haha'], ['😅', 'sweat laugh relief'],
      ['🤣', 'rofl rolling laughing'], ['😂', 'joy tears laugh cry'], ['🙂', 'slight smile'],
      ['🙃', 'upside down silly'], ['😉', 'wink flirt'], ['😊', 'blush smile happy'],
      ['😇', 'halo angel innocent'], ['🥰', 'hearts love adore'], ['😍', 'heart eyes love'],
      ['🤩', 'star struck excited'], ['😘', 'kiss blow love'], ['😗', 'kissing'],
      ['😚', 'kissing closed eyes'], ['😙', 'kissing smile'], ['🥲', 'tear happy sad'],
      ['😋', 'yum tasty tongue delicious'], ['😛', 'tongue out'], ['😜', 'wink tongue joke'],
      ['🤪', 'zany crazy silly'], ['😝', 'squint tongue'], ['🤑', 'money mouth rich cash'],
      ['🤗', 'hug hands'], ['🤭', 'hand over mouth oops giggle'], ['🤫', 'shush quiet secret'],
      ['🤔', 'thinking hmm ponder'], ['🤐', 'zipper mouth silent'], ['🤨', 'raised eyebrow suspicious'],
      ['😐', 'neutral meh'], ['😑', 'expressionless blank'], ['😶', 'no mouth speechless'],
      ['😏', 'smirk sly'], ['😒', 'unamused annoyed'], ['🙄', 'eye roll'],
      ['😬', 'grimace awkward'], ['🤥', 'lying pinocchio'], ['😌', 'relieved calm'],
      ['😔', 'pensive sad'], ['😪', 'sleepy tired'], ['🤤', 'drool'],
      ['😴', 'sleeping zzz asleep'], ['😷', 'mask sick medical'], ['🤒', 'thermometer sick fever'],
      ['🤕', 'bandage hurt injured'], ['🤢', 'nauseated sick green'], ['🤮', 'vomit sick'],
      ['🤧', 'sneeze tissue'], ['🥵', 'hot heat sweating'], ['🥶', 'cold freezing'],
      ['🥴', 'woozy drunk dizzy'], ['😵', 'dizzy knocked out'], ['🤯', 'mind blown explode'],
      ['🤠', 'cowboy hat'], ['🥳', 'party celebrate birthday'], ['😎', 'sunglasses cool'],
      ['🤓', 'nerd glasses geek'], ['🧐', 'monocle inspect'], ['😕', 'confused'],
      ['😟', 'worried'], ['🙁', 'slight frown'], ['😮', 'open mouth surprise'],
      ['😯', 'hushed surprised'], ['😲', 'astonished shocked'], ['😳', 'flushed embarrassed'],
      ['🥺', 'pleading puppy eyes beg'], ['😦', 'frowning open mouth'], ['😧', 'anguished'],
      ['😨', 'fearful scared'], ['😰', 'anxious sweat'], ['😥', 'sad relieved'],
      ['😢', 'cry tear sad'], ['😭', 'sobbing bawling cry'], ['😱', 'scream fear shock'],
      ['😖', 'confounded'], ['😣', 'persevere struggle'], ['😞', 'disappointed'],
      ['😓', 'downcast sweat'], ['😩', 'weary tired'], ['😫', 'tired exhausted'],
      ['🥱', 'yawn bored'], ['😤', 'triumph steam determined'], ['😡', 'angry rage mad'],
      ['😠', 'angry mad'], ['🤬', 'cursing swearing'], ['😈', 'devil smiling imp'],
      ['👿', 'imp angry devil'], ['💀', 'skull dead'], ['☠️', 'skull crossbones danger'],
      ['💩', 'poop'], ['🤡', 'clown'], ['👹', 'ogre monster'],
      ['👻', 'ghost halloween boo'], ['👽', 'alien ufo'], ['🤖', 'robot bot ai'],
      ['😺', 'cat grin'], ['😻', 'cat heart eyes'], ['🙈', 'see no evil monkey'],
      ['🙉', 'hear no evil monkey'], ['🙊', 'speak no evil monkey'], ['💋', 'kiss lips'],
      ['💌', 'love letter'], ['💘', 'heart arrow cupid'], ['💝', 'heart ribbon gift'],
      ['💖', 'sparkling heart'], ['💗', 'growing heart'], ['💓', 'beating heart'],
      ['💞', 'revolving hearts'], ['💕', 'two hearts'], ['❤️', 'red heart love'],
      ['🧡', 'orange heart'], ['💛', 'yellow heart'], ['💚', 'green heart'],
      ['💙', 'blue heart'], ['💜', 'purple heart'], ['🖤', 'black heart'],
      ['🤍', 'white heart'], ['🤎', 'brown heart'], ['💔', 'broken heart'],
      ['❣️', 'heart exclamation'], ['💯', 'hundred perfect score'], ['💢', 'anger symbol'],
      ['💥', 'collision boom explode'], ['💫', 'dizzy star'], ['💦', 'sweat droplets water'],
      ['💨', 'dash wind fast'], ['🕳️', 'hole'], ['💬', 'speech balloon chat'],
      ['💭', 'thought balloon'], ['🗯️', 'anger balloon'], ['💤', 'zzz sleep'],
    ],
  },
  {
    key: 'people',
    label: 'People',
    tabIcon: '👋',
    items: [
      ['👋', 'wave hello hi bye'], ['🤚', 'raised back hand'], ['🖐️', 'hand fingers splayed'],
      ['✋', 'raised hand stop high five'], ['🖖', 'vulcan spock'], ['👌', 'ok perfect'],
      ['🤌', 'pinched fingers italian'], ['🤏', 'pinch small little'], ['✌️', 'victory peace'],
      ['🤞', 'crossed fingers luck hope'], ['🤟', 'love you gesture'], ['🤘', 'rock horns'],
      ['🤙', 'call me shaka'], ['👈', 'point left'], ['👉', 'point right'],
      ['👆', 'point up'], ['👇', 'point down'], ['☝️', 'index up'],
      ['👍', 'thumbs up yes good like'], ['👎', 'thumbs down no bad'], ['✊', 'fist raised power'],
      ['👊', 'fist bump punch'], ['🤛', 'left fist'], ['🤜', 'right fist'],
      ['👏', 'clap applause bravo'], ['🙌', 'raising hands praise celebrate'], ['👐', 'open hands'],
      ['🤲', 'palms up'], ['🤝', 'handshake deal agreement'], ['🙏', 'pray thanks please namaste'],
      ['✍️', 'writing hand sign'], ['💅', 'nail polish manicure'], ['🤳', 'selfie'],
      ['💪', 'muscle strong flex gym'], ['🦵', 'leg'], ['🦶', 'foot'],
      ['👂', 'ear listen'], ['👃', 'nose smell'], ['🧠', 'brain smart think'],
      ['🫀', 'anatomical heart organ'], ['🦷', 'tooth dentist'], ['🦴', 'bone'],
      ['👀', 'eyes look watch'], ['👁️', 'eye'], ['👅', 'tongue'],
      ['👄', 'mouth lips'], ['👶', 'baby infant'], ['🧒', 'child kid'],
      ['👦', 'boy'], ['👧', 'girl'], ['🧑', 'person adult'],
      ['👨', 'man'], ['👩', 'woman'], ['🧓', 'older person'],
      ['👴', 'old man grandpa'], ['👵', 'old woman grandma'], ['🙍', 'person frowning'],
      ['🙎', 'person pouting'], ['🙅', 'no gesture forbidden'], ['🙆', 'ok gesture'],
      ['💁', 'tipping hand info sassy'], ['🙋', 'raising hand question'], ['🧏', 'deaf person'],
      ['🙇', 'bowing sorry'], ['🤦', 'facepalm'], ['🤷', 'shrug dunno'],
      ['👮', 'police officer cop'], ['🕵️', 'detective spy'], ['💂', 'guard'],
      ['🥷', 'ninja'], ['👷', 'construction worker builder'], ['🤴', 'prince'],
      ['👸', 'princess'], ['👳', 'turban'], ['🧕', 'headscarf hijab'],
      ['🤵', 'tuxedo groom'], ['👰', 'bride veil wedding'], ['🤰', 'pregnant'],
      ['🍼', 'baby bottle milk'], ['👼', 'baby angel'], ['🎅', 'santa christmas'],
      ['🤶', 'mrs claus christmas'], ['🦸', 'superhero'], ['🦹', 'supervillain'],
      ['🧙', 'mage wizard'], ['🧚', 'fairy'], ['🧛', 'vampire'],
      ['🧜', 'merperson mermaid'], ['🧝', 'elf'], ['💆', 'massage spa'],
      ['💇', 'haircut barber salon'], ['🚶', 'walking pedestrian'], ['🧍', 'standing person'],
      ['🧎', 'kneeling'], ['🏃', 'running run exercise'], ['💃', 'dancer dancing'],
      ['🕺', 'man dancing'], ['👯', 'bunny ears partying'], ['🧖', 'sauna steam spa'],
      ['🧗', 'climbing'], ['👨‍👩‍👧‍👦', 'family parents children'], ['👪', 'family'],
      ['🗣️', 'speaking head talk'], ['👤', 'silhouette person user'], ['👥', 'silhouettes people users'],
      ['🫂', 'people hugging'], ['👣', 'footprints'],
    ],
  },
  {
    key: 'animals',
    label: 'Nature',
    tabIcon: '🐶',
    items: [
      ['🐶', 'dog puppy pet'], ['🐱', 'cat kitten pet'], ['🐭', 'mouse'],
      ['🐹', 'hamster'], ['🐰', 'rabbit bunny'], ['🦊', 'fox'],
      ['🐻', 'bear'], ['🐼', 'panda'], ['🐻‍❄️', 'polar bear'],
      ['🐨', 'koala'], ['🐯', 'tiger'], ['🦁', 'lion'],
      ['🐮', 'cow'], ['🐷', 'pig'], ['🐽', 'pig nose'],
      ['🐸', 'frog'], ['🐵', 'monkey'], ['🙈', 'monkey see no evil'],
      ['🐒', 'monkey full'], ['🐔', 'chicken hen'], ['🐧', 'penguin'],
      ['🐦', 'bird'], ['🐤', 'chick baby bird'], ['🦆', 'duck'],
      ['🦅', 'eagle'], ['🦉', 'owl'], ['🦇', 'bat'],
      ['🐺', 'wolf'], ['🐗', 'boar'], ['🐴', 'horse'],
      ['🦄', 'unicorn'], ['🐝', 'bee honey'], ['🪲', 'beetle bug'],
      ['🐛', 'caterpillar bug'], ['🦋', 'butterfly'], ['🐌', 'snail slow'],
      ['🐞', 'ladybug'], ['🐜', 'ant'], ['🕷️', 'spider'],
      ['🦂', 'scorpion'], ['🐢', 'turtle'], ['🐍', 'snake'],
      ['🦎', 'lizard gecko'], ['🦖', 'dinosaur trex'], ['🐙', 'octopus'],
      ['🦑', 'squid'], ['🦐', 'shrimp'], ['🦀', 'crab'],
      ['🐡', 'blowfish'], ['🐠', 'tropical fish'], ['🐟', 'fish'],
      ['🐬', 'dolphin'], ['🐳', 'whale'], ['🦈', 'shark'],
      ['🐊', 'crocodile'], ['🐅', 'tiger full'], ['🦓', 'zebra'],
      ['🦍', 'gorilla'], ['🦧', 'orangutan'], ['🐘', 'elephant'],
      ['🦛', 'hippo'], ['🦏', 'rhino'], ['🐪', 'camel'],
      ['🦒', 'giraffe'], ['🦘', 'kangaroo'], ['🐃', 'buffalo'],
      ['🐄', 'cow full'], ['🐎', 'racehorse'], ['🐖', 'pig full'],
      ['🐏', 'ram'], ['🐑', 'sheep wool'], ['🦙', 'llama alpaca'],
      ['🐐', 'goat'], ['🦌', 'deer'], ['🐕', 'dog full'],
      ['🦮', 'guide dog'], ['🐩', 'poodle'], ['🐈', 'cat full'],
      ['🐓', 'rooster'], ['🦃', 'turkey'], ['🦚', 'peacock'],
      ['🦜', 'parrot'], ['🦢', 'swan'], ['🕊️', 'dove peace'],
      ['🐇', 'rabbit full'], ['🦝', 'raccoon'], ['🦨', 'skunk'],
      ['🦡', 'badger'], ['🐁', 'mouse full'], ['🐿️', 'chipmunk squirrel'],
      ['🦔', 'hedgehog'], ['🐾', 'paw prints pet animal'], ['🌵', 'cactus'],
      ['🎄', 'christmas tree'], ['🌲', 'evergreen tree'], ['🌳', 'tree'],
      ['🌴', 'palm tree'], ['🪴', 'potted plant'], ['🌱', 'seedling sprout grow'],
      ['🌿', 'herb leaves'], ['☘️', 'shamrock'], ['🍀', 'four leaf clover luck'],
      ['🎍', 'bamboo'], ['🍃', 'leaves wind'], ['🍂', 'fallen leaves autumn'],
      ['🍁', 'maple leaf canada'], ['🍄', 'mushroom'], ['🌾', 'wheat grain'],
      ['💐', 'bouquet flowers'], ['🌷', 'tulip'], ['🌹', 'rose'],
      ['🥀', 'wilted flower'], ['🌺', 'hibiscus'], ['🌸', 'cherry blossom sakura'],
      ['🌼', 'daisy blossom'], ['🌻', 'sunflower'], ['🌞', 'sun face'],
      ['🌝', 'full moon face'], ['🌛', 'first quarter moon face'], ['🌜', 'last quarter moon face'],
      ['🌚', 'new moon face'], ['🌕', 'full moon'], ['🌙', 'crescent moon night'],
      ['🌎', 'earth americas globe world'], ['🌍', 'earth africa globe world'], ['🌏', 'earth asia globe world'],
      ['💫', 'dizzy stars'], ['⭐', 'star'], ['🌟', 'glowing star'],
      ['✨', 'sparkles magic shine'], ['⚡', 'lightning bolt zap power'], ['☄️', 'comet'],
      ['🔥', 'fire hot lit flame'], ['🌪️', 'tornado'], ['🌈', 'rainbow'],
      ['☀️', 'sun sunny'], ['⛅', 'sun behind cloud'], ['☁️', 'cloud'],
      ['🌧️', 'rain cloud'], ['⛈️', 'thunderstorm'], ['❄️', 'snowflake cold winter'],
      ['☃️', 'snowman'], ['💧', 'droplet water'], ['🌊', 'wave ocean sea'],
    ],
  },
  {
    key: 'food',
    label: 'Food',
    tabIcon: '🍔',
    items: [
      ['🍏', 'green apple'], ['🍎', 'apple fruit'], ['🍐', 'pear'],
      ['🍊', 'orange tangerine'], ['🍋', 'lemon'], ['🍌', 'banana'],
      ['🍉', 'watermelon'], ['🍇', 'grapes'], ['🍓', 'strawberry'],
      ['🫐', 'blueberries'], ['🍈', 'melon'], ['🍒', 'cherries'],
      ['🍑', 'peach'], ['🥭', 'mango'], ['🍍', 'pineapple'],
      ['🥥', 'coconut'], ['🥝', 'kiwi'], ['🍅', 'tomato'],
      ['🍆', 'aubergine eggplant'], ['🥑', 'avocado'], ['🥦', 'broccoli'],
      ['🥬', 'leafy greens'], ['🥒', 'cucumber'], ['🌶️', 'chilli pepper spicy hot'],
      ['🫑', 'bell pepper'], ['🌽', 'corn'], ['🥕', 'carrot'],
      ['🧄', 'garlic'], ['🧅', 'onion'], ['🥔', 'potato'],
      ['🍠', 'sweet potato'], ['🥐', 'croissant'], ['🥯', 'bagel'],
      ['🍞', 'bread loaf'], ['🥖', 'baguette'], ['🥨', 'pretzel'],
      ['🧀', 'cheese'], ['🥚', 'egg'], ['🍳', 'cooking fried egg breakfast'],
      ['🧈', 'butter'], ['🥞', 'pancakes'], ['🧇', 'waffle'],
      ['🥓', 'bacon'], ['🥩', 'steak meat'], ['🍗', 'poultry leg chicken'],
      ['🍖', 'meat bone'], ['🌭', 'hot dog'], ['🍔', 'burger hamburger fast food'],
      ['🍟', 'fries chips'], ['🍕', 'pizza'], ['🫓', 'flatbread'],
      ['🥪', 'sandwich'], ['🥙', 'wrap kebab'], ['🧆', 'falafel'],
      ['🌮', 'taco'], ['🌯', 'burrito'], ['🫔', 'tamale'],
      ['🥗', 'salad healthy'], ['🥘', 'paella pan food'], ['🫕', 'fondue'],
      ['🍝', 'spaghetti pasta'], ['🍜', 'ramen noodles'], ['🍲', 'stew soup'],
      ['🍛', 'curry rice'], ['🍣', 'sushi'], ['🍱', 'bento box'],
      ['🥟', 'dumpling'], ['🦪', 'oyster'], ['🍤', 'fried shrimp tempura'],
      ['🍙', 'rice ball onigiri'], ['🍚', 'rice'], ['🍘', 'rice cracker'],
      ['🥠', 'fortune cookie'], ['🥮', 'moon cake'], ['🍢', 'oden skewer'],
      ['🍡', 'dango'], ['🍧', 'shaved ice'], ['🍨', 'ice cream'],
      ['🍦', 'soft serve ice cream'], ['🥧', 'pie'], ['🧁', 'cupcake'],
      ['🍰', 'cake slice shortcake'], ['🎂', 'birthday cake'], ['🍮', 'custard flan'],
      ['🍭', 'lollipop'], ['🍬', 'sweets candy'], ['🍫', 'chocolate'],
      ['🍿', 'popcorn cinema'], ['🍩', 'doughnut donut'], ['🍪', 'cookie biscuit'],
      ['🌰', 'chestnut'], ['🥜', 'peanuts nuts'], ['🍯', 'honey'],
      ['🥛', 'milk glass'], ['🍼', 'baby bottle'], ['☕', 'coffee tea hot drink cafe'],
      ['🫖', 'teapot'], ['🍵', 'green tea matcha'], ['🧃', 'juice box'],
      ['🥤', 'soft drink cup soda'], ['🧋', 'bubble tea boba'], ['🍶', 'sake'],
      ['🍺', 'beer pint pub'], ['🍻', 'cheers beers'], ['🥂', 'champagne cheers celebrate'],
      ['🍷', 'wine glass'], ['🥃', 'whisky tumbler'], ['🍸', 'cocktail martini'],
      ['🍹', 'tropical drink'], ['🍾', 'champagne bottle'], ['🧊', 'ice cube'],
      ['🥄', 'spoon'], ['🍴', 'fork knife cutlery restaurant'], ['🍽️', 'plate cutlery dining'],
      ['🥣', 'bowl spoon cereal'], ['🥡', 'takeaway box takeout'], ['🥢', 'chopsticks'],
      ['🧂', 'salt'],
    ],
  },
  {
    key: 'travel',
    label: 'Travel',
    tabIcon: '✈️',
    items: [
      ['🚗', 'car auto drive'], ['🚕', 'taxi cab'], ['🚙', 'suv'],
      ['🚌', 'bus'], ['🚎', 'trolleybus'], ['🏎️', 'racing car'],
      ['🚓', 'police car'], ['🚑', 'ambulance'], ['🚒', 'fire engine'],
      ['🚐', 'minibus van'], ['🛻', 'pickup truck'], ['🚚', 'delivery truck'],
      ['🚛', 'lorry articulated truck'], ['🚜', 'tractor farm'], ['🛵', 'scooter moped'],
      ['🏍️', 'motorcycle'], ['🛺', 'auto rickshaw tuktuk'], ['🚲', 'bicycle bike cycling'],
      ['🛴', 'kick scooter'], ['🛹', 'skateboard'], ['🚨', 'siren emergency'],
      ['🚔', 'police car oncoming'], ['🚍', 'bus oncoming'], ['🚘', 'car oncoming'],
      ['🚖', 'taxi oncoming'], ['🚡', 'aerial tramway'], ['🚠', 'mountain cableway'],
      ['🚟', 'suspension railway'], ['🚃', 'railway car'], ['🚋', 'tram car'],
      ['🚞', 'mountain railway'], ['🚝', 'monorail'], ['🚄', 'bullet train'],
      ['🚅', 'bullet train nose'], ['🚈', 'light rail'], ['🚂', 'steam locomotive train'],
      ['🚆', 'train'], ['🚇', 'metro underground tube subway'], ['🚊', 'tram'],
      ['🚉', 'station'], ['✈️', 'plane flight travel airport'], ['🛫', 'departure takeoff'],
      ['🛬', 'arrival landing'], ['🛩️', 'small plane'], ['💺', 'seat flight'],
      ['🚁', 'helicopter'], ['🚀', 'rocket launch'], ['🛸', 'ufo flying saucer'],
      ['🛰️', 'satellite'], ['🚢', 'ship cruise'], ['⛴️', 'ferry'],
      ['🛥️', 'motor boat'], ['🚤', 'speedboat'], ['⛵', 'sailboat yacht'],
      ['🛶', 'canoe kayak'], ['⚓', 'anchor'], ['⛽', 'fuel petrol gas station'],
      ['🚏', 'bus stop'], ['🚦', 'traffic light'], ['🚧', 'construction roadworks'],
      ['🗺️', 'map world'], ['🧭', 'compass'], ['🗿', 'moai statue'],
      ['🗽', 'statue of liberty'], ['🗼', 'tokyo tower'], ['🏰', 'castle'],
      ['🏯', 'japanese castle'], ['🏟️', 'stadium'], ['🎡', 'ferris wheel'],
      ['🎢', 'roller coaster theme park'], ['🎠', 'carousel'], ['⛲', 'fountain'],
      ['⛱️', 'beach umbrella'], ['🏖️', 'beach holiday vacation'], ['🏝️', 'desert island'],
      ['🏜️', 'desert'], ['🌋', 'volcano'], ['⛰️', 'mountain'],
      ['🏔️', 'snow mountain'], ['🗻', 'mount fuji'], ['🏕️', 'camping tent'],
      ['⛺', 'tent'], ['🏠', 'house home'], ['🏡', 'house garden home'],
      ['🏘️', 'houses neighbourhood'], ['🏚️', 'derelict house'], ['🏗️', 'construction crane'],
      ['🏭', 'factory'], ['🏢', 'office building work'], ['🏬', 'department store shopping'],
      ['🏣', 'post office'], ['🏤', 'european post office'], ['🏥', 'hospital'],
      ['🏦', 'bank'], ['🏨', 'hotel'], ['🏪', 'convenience store shop'],
      ['🏫', 'school'], ['🏩', 'love hotel'], ['💒', 'wedding chapel'],
      ['⛪', 'church'], ['🕌', 'mosque'], ['🕍', 'synagogue'],
      ['🛕', 'hindu temple'], ['🕋', 'kaaba'], ['⛩️', 'shinto shrine'],
      ['🌁', 'foggy'], ['🌃', 'night stars city'], ['🏙️', 'cityscape city'],
      ['🌄', 'sunrise mountains'], ['🌅', 'sunrise'], ['🌆', 'dusk cityscape'],
      ['🌇', 'sunset'], ['🌉', 'bridge night'], ['🎑', 'moon viewing'],
      ['🎇', 'sparkler'], ['🎆', 'fireworks'], ['🧳', 'luggage suitcase travel'],
      ['🛎️', 'bellhop bell hotel'], ['🛌', 'sleeping accommodation'], ['🛏️', 'bed'],
      ['🚪', 'door'], ['🪑', 'chair'], ['🚿', 'shower'],
      ['🛁', 'bath'], ['🚽', 'toilet'], ['🧻', 'toilet paper'],
    ],
  },
  {
    key: 'activities',
    label: 'Activity',
    tabIcon: '⚽',
    items: [
      ['⚽', 'football soccer'], ['🏀', 'basketball'], ['🏈', 'american football'],
      ['⚾', 'baseball'], ['🥎', 'softball'], ['🎾', 'tennis'],
      ['🏐', 'volleyball'], ['🏉', 'rugby'], ['🥏', 'frisbee'],
      ['🎱', 'pool billiards 8 ball'], ['🪀', 'yoyo'], ['🏓', 'table tennis ping pong'],
      ['🏸', 'badminton'], ['🏒', 'ice hockey'], ['🏑', 'field hockey'],
      ['🥍', 'lacrosse'], ['🏏', 'cricket'], ['🥅', 'goal net'],
      ['⛳', 'golf'], ['🪁', 'kite'], ['🏹', 'bow arrow archery'],
      ['🎣', 'fishing'], ['🤿', 'diving mask snorkel'], ['🥊', 'boxing glove'],
      ['🥋', 'martial arts karate judo'], ['🎽', 'running shirt'], ['🛹', 'skateboard'],
      ['🛼', 'roller skate'], ['🛷', 'sled'], ['⛸️', 'ice skate'],
      ['🥌', 'curling stone'], ['🎿', 'skis skiing'], ['⛷️', 'skier'],
      ['🏂', 'snowboarder'], ['🏋️', 'weightlifting gym workout'], ['🤸', 'cartwheel gymnastics'],
      ['🤼', 'wrestling'], ['🤽', 'water polo'], ['🤾', 'handball'],
      ['🤹', 'juggling'], ['🧘', 'yoga meditation lotus'], ['🏄', 'surfing'],
      ['🏊', 'swimming'], ['🚴', 'cycling bike'], ['🚵', 'mountain biking'],
      ['🧗', 'climbing'], ['🏇', 'horse racing'], ['🏆', 'trophy win champion'],
      ['🥇', 'gold medal first'], ['🥈', 'silver medal second'], ['🥉', 'bronze medal third'],
      ['🏅', 'medal'], ['🎖️', 'military medal'], ['🎗️', 'ribbon awareness'],
      ['🎫', 'ticket'], ['🎟️', 'admission tickets'], ['🎪', 'circus tent'],
      ['🤹‍♀️', 'juggling woman'], ['🎭', 'performing arts theatre drama'], ['🩰', 'ballet shoes'],
      ['🎨', 'art palette paint'], ['🎬', 'clapper board film movie cinema'], ['🎤', 'microphone sing karaoke'],
      ['🎧', 'headphones music listen'], ['🎼', 'musical score'], ['🎹', 'piano keyboard'],
      ['🥁', 'drum'], ['🎷', 'saxophone'], ['🎺', 'trumpet'],
      ['🎸', 'guitar'], ['🪕', 'banjo'], ['🎻', 'violin'],
      ['🎲', 'dice game'], ['♟️', 'chess pawn'], ['🎯', 'target darts bullseye goal'],
      ['🎳', 'bowling'], ['🎮', 'video game controller gaming'], ['🕹️', 'joystick arcade'],
      ['🎰', 'slot machine gambling'], ['🧩', 'puzzle piece jigsaw'], ['🧸', 'teddy bear toy'],
      ['🪅', 'pinata'], ['🎁', 'gift present birthday'], ['🎀', 'ribbon bow'],
      ['🎊', 'confetti ball celebrate'], ['🎉', 'party popper celebrate'], ['🎈', 'balloon'],
      ['🎃', 'jack o lantern halloween pumpkin'], ['🧨', 'firecracker'], ['🪄', 'magic wand'],
    ],
  },
  {
    key: 'objects',
    label: 'Objects',
    tabIcon: '💡',
    items: [
      ['⌚', 'watch time'], ['📱', 'phone mobile smartphone'], ['💻', 'laptop computer work'],
      ['⌨️', 'keyboard'], ['🖥️', 'desktop computer monitor'], ['🖨️', 'printer'],
      ['🖱️', 'mouse computer'], ['💽', 'minidisc'], ['💾', 'floppy disk save'],
      ['💿', 'cd disc'], ['📀', 'dvd'], ['🧮', 'abacus maths'],
      ['🎥', 'movie camera'], ['📷', 'camera photo'], ['📸', 'camera flash photo'],
      ['📹', 'video camera'], ['📼', 'videocassette'], ['🔍', 'magnifying glass search'],
      ['🔎', 'magnifying glass right search'], ['🕯️', 'candle'], ['💡', 'light bulb idea electricity'],
      ['🔦', 'torch flashlight'], ['🏮', 'lantern'], ['🪔', 'diya lamp'],
      ['📔', 'notebook decorative'], ['📕', 'closed book'], ['📖', 'open book read'],
      ['📗', 'green book'], ['📘', 'blue book'], ['📙', 'orange book'],
      ['📚', 'books library study'], ['📓', 'notebook'], ['📒', 'ledger accounts'],
      ['📃', 'page curl document'], ['📜', 'scroll'], ['📄', 'page document file'],
      ['📰', 'newspaper news'], ['🗞️', 'rolled newspaper'], ['📑', 'bookmark tabs'],
      ['🔖', 'bookmark'], ['🏷️', 'label tag price'], ['💰', 'money bag savings cash'],
      ['🪙', 'coin money'], ['💴', 'yen banknote'], ['💵', 'dollar banknote money cash'],
      ['💶', 'euro banknote'], ['💷', 'pound banknote money sterling'], ['💸', 'money with wings spend'],
      ['💳', 'credit card payment'], ['🧾', 'receipt bill invoice expense'], ['💎', 'gem diamond'],
      ['⚖️', 'scales balance justice'], ['🪜', 'ladder'], ['🧰', 'toolbox'],
      ['🔧', 'spanner wrench'], ['🔨', 'hammer'], ['⚒️', 'hammer pick'],
      ['🛠️', 'hammer wrench tools diy'], ['⛏️', 'pick'], ['🪛', 'screwdriver'],
      ['🔩', 'nut bolt'], ['⚙️', 'gear settings cog'], ['🧱', 'brick'],
      ['⛓️', 'chains'], ['🧲', 'magnet'], ['🔫', 'water pistol'],
      ['💣', 'bomb'], ['🧯', 'fire extinguisher'], ['🪓', 'axe'],
      ['🔪', 'knife kitchen'], ['🗡️', 'dagger'], ['🛡️', 'shield protect'],
      ['🚬', 'cigarette smoking'], ['⚰️', 'coffin'], ['🏺', 'amphora'],
      ['🔮', 'crystal ball fortune'], ['📿', 'prayer beads'], ['🧿', 'nazar amulet'],
      ['💈', 'barber pole'], ['⚗️', 'alembic chemistry'], ['🔭', 'telescope'],
      ['🔬', 'microscope science'], ['🕳️', 'hole'], ['💊', 'pill medicine health'],
      ['💉', 'syringe injection vaccine'], ['🩸', 'blood drop'], ['🩹', 'plaster bandage'],
      ['🩺', 'stethoscope doctor health'], ['🌡️', 'thermometer'], ['🧬', 'dna'],
      ['🦠', 'microbe germ virus'], ['🧫', 'petri dish'], ['🧪', 'test tube'],
      ['🧹', 'broom cleaning'], ['🧺', 'basket laundry'], ['🧻', 'toilet paper'],
      ['🧼', 'soap'], ['🪥', 'toothbrush'], ['🧽', 'sponge'],
      ['🪣', 'bucket'], ['🚰', 'drinking water'], ['🛒', 'shopping trolley cart groceries'],
      ['🛍️', 'shopping bags retail'], ['🎒', 'backpack school bag'], ['👝', 'clutch bag pouch'],
      ['👛', 'purse'], ['👜', 'handbag'], ['💼', 'briefcase work business job'],
      ['🧳', 'suitcase luggage'], ['👓', 'glasses'], ['🕶️', 'sunglasses'],
      ['🥽', 'goggles'], ['🥼', 'lab coat'], ['🦺', 'safety vest'],
      ['👔', 'necktie shirt'], ['👕', 'tshirt clothes'], ['👖', 'jeans trousers'],
      ['🧣', 'scarf'], ['🧤', 'gloves'], ['🧥', 'coat jacket'],
      ['🧦', 'socks'], ['👗', 'dress'], ['👘', 'kimono'],
      ['🥻', 'sari'], ['🩱', 'swimsuit'], ['👙', 'bikini'],
      ['👚', 'blouse'], ['👞', 'shoe formal'], ['👟', 'trainers sneakers running shoe'],
      ['🥾', 'hiking boot'], ['👠', 'high heel'], ['👡', 'sandal'],
      ['🩴', 'flip flop thong'], ['👢', 'boot'], ['👑', 'crown king queen'],
      ['👒', 'hat woman'], ['🎩', 'top hat'], ['🎓', 'graduation cap university education'],
      ['🧢', 'cap baseball'], ['⛑️', 'rescue helmet'], ['💄', 'lipstick makeup'],
      ['💍', 'ring engagement'], ['📞', 'telephone receiver call'], ['☎️', 'telephone'],
      ['📟', 'pager'], ['📠', 'fax'], ['🔋', 'battery'],
      ['🔌', 'plug electricity power'], ['📡', 'satellite antenna'], ['📺', 'television tv'],
      ['📻', 'radio'], ['🎙️', 'studio microphone podcast'], ['⏰', 'alarm clock'],
      ['⏱️', 'stopwatch'], ['⏳', 'hourglass time'], ['⌛', 'hourglass done'],
      ['📅', 'calendar date'], ['📆', 'calendar tear off'], ['🗓️', 'spiral calendar'],
      ['📇', 'card index'], ['📈', 'chart increasing growth up'], ['📉', 'chart decreasing down loss'],
      ['📊', 'bar chart analytics stats'], ['📋', 'clipboard list'], ['📌', 'pushpin'],
      ['📍', 'round pin location'], ['📎', 'paperclip'], ['✂️', 'scissors cut'],
      ['📁', 'folder file'], ['📂', 'open folder'], ['🗂️', 'card index dividers'],
      ['🗃️', 'card file box'], ['🗄️', 'file cabinet'], ['🗑️', 'wastebasket bin delete trash'],
      ['🔒', 'locked padlock secure'], ['🔓', 'unlocked'], ['🔐', 'locked with key'],
      ['🔑', 'key'], ['🗝️', 'old key'], ['🔔', 'bell notification'],
      ['🔕', 'bell muted'], ['📣', 'megaphone announce'], ['📢', 'loudspeaker'],
      ['✉️', 'envelope email mail'], ['📧', 'email'], ['📨', 'incoming envelope'],
      ['📩', 'envelope arrow'], ['📤', 'outbox tray'], ['📥', 'inbox tray'],
      ['📦', 'package box parcel delivery'], ['📫', 'mailbox'], ['📮', 'postbox'],
      ['🖊️', 'pen'], ['🖋️', 'fountain pen'], ['✒️', 'nib'],
      ['🖌️', 'paintbrush'], ['🖍️', 'crayon'], ['📝', 'memo note write'],
      ['✏️', 'pencil write'], ['📏', 'ruler straight'], ['📐', 'triangular ruler'],
    ],
  },
  {
    key: 'symbols',
    label: 'Symbols',
    tabIcon: '❤️',
    items: [
      ['❤️', 'red heart love'], ['💯', 'hundred perfect'], ['✅', 'check mark green done tick'],
      ['☑️', 'ballot check'], ['✔️', 'check mark tick'], ['❌', 'cross mark no wrong'],
      ['❎', 'cross mark button'], ['➕', 'plus add'], ['➖', 'minus subtract'],
      ['➗', 'divide'], ['✖️', 'multiply'], ['🟰', 'equals'],
      ['♾️', 'infinity'], ['❓', 'question mark'], ['❔', 'white question'],
      ['❗', 'exclamation'], ['❕', 'white exclamation'], ['‼️', 'double exclamation'],
      ['⁉️', 'exclamation question'], ['⚠️', 'warning caution'], ['🚸', 'children crossing'],
      ['⛔', 'no entry'], ['🚫', 'prohibited forbidden'], ['🚭', 'no smoking'],
      ['☢️', 'radioactive'], ['☣️', 'biohazard'], ['⬆️', 'up arrow'],
      ['⬇️', 'down arrow'], ['⬅️', 'left arrow'], ['➡️', 'right arrow'],
      ['↗️', 'up right arrow'], ['↘️', 'down right arrow'], ['↙️', 'down left arrow'],
      ['↖️', 'up left arrow'], ['↕️', 'up down arrow'], ['↔️', 'left right arrow'],
      ['🔄', 'counterclockwise arrows refresh'], ['🔃', 'clockwise arrows'], ['🔙', 'back'],
      ['🔚', 'end'], ['🔛', 'on'], ['🔝', 'top'],
      ['🔜', 'soon'], ['🔁', 'repeat loop recurring'], ['🔂', 'repeat one'],
      ['▶️', 'play'], ['⏸️', 'pause'], ['⏹️', 'stop'],
      ['⏺️', 'record'], ['⏭️', 'next track'], ['⏮️', 'previous track'],
      ['🔀', 'shuffle'], ['🔼', 'up button'], ['🔽', 'down button'],
      ['🎦', 'cinema'], ['🔅', 'dim brightness'], ['🔆', 'bright brightness'],
      ['📶', 'signal bars wifi'], ['📳', 'vibration mode'], ['📴', 'phone off'],
      ['♻️', 'recycle'], ['⚜️', 'fleur de lis'], ['🔱', 'trident'],
      ['📛', 'name badge'], ['🔰', 'japanese beginner'], ['⭕', 'hollow red circle'],
      ['✳️', 'eight spoked asterisk'], ['✴️', 'eight pointed star'], ['❇️', 'sparkle'],
      ['©️', 'copyright'], ['®️', 'registered'], ['™️', 'trade mark'],
      ['#️⃣', 'hash keycap'], ['*️⃣', 'asterisk keycap'], ['0️⃣', 'zero'],
      ['1️⃣', 'one'], ['2️⃣', 'two'], ['3️⃣', 'three'],
      ['4️⃣', 'four'], ['5️⃣', 'five'], ['6️⃣', 'six'],
      ['7️⃣', 'seven'], ['8️⃣', 'eight'], ['9️⃣', 'nine'],
      ['🔟', 'ten'], ['🆔', 'id'], ['🆕', 'new'],
      ['🆓', 'free'], ['🆒', 'cool'], ['🆗', 'ok'],
      ['🆙', 'up'], ['🅰️', 'a button'], ['🅱️', 'b button'],
      ['🈹', 'discount'], ['🈚', 'free of charge'], ['🉐', 'bargain'],
      ['💠', 'diamond with dot'], ['🔶', 'large orange diamond'], ['🔷', 'large blue diamond'],
      ['🔴', 'red circle'], ['🟠', 'orange circle'], ['🟡', 'yellow circle'],
      ['🟢', 'green circle'], ['🔵', 'blue circle'], ['🟣', 'purple circle'],
      ['🟤', 'brown circle'], ['⚫', 'black circle'], ['⚪', 'white circle'],
      ['🟥', 'red square'], ['🟧', 'orange square'], ['🟨', 'yellow square'],
      ['🟩', 'green square'], ['🟦', 'blue square'], ['🟪', 'purple square'],
      ['⬛', 'black square'], ['⬜', 'white square'], ['♠️', 'spade'],
      ['♥️', 'heart suit'], ['♦️', 'diamond suit'], ['♣️', 'club suit'],
      ['🃏', 'joker'], ['🀄', 'mahjong'], ['🎴', 'flower cards'],
      ['♈', 'aries'], ['♉', 'taurus'], ['♊', 'gemini'],
      ['♋', 'cancer'], ['♌', 'leo'], ['♍', 'virgo'],
      ['♎', 'libra'], ['♏', 'scorpio'], ['♐', 'sagittarius'],
      ['♑', 'capricorn'], ['♒', 'aquarius'], ['♓', 'pisces'],
      ['⛎', 'ophiuchus'], ['☮️', 'peace'], ['☯️', 'yin yang'],
      ['✝️', 'latin cross'], ['☪️', 'star and crescent'], ['🕉️', 'om'],
      ['✡️', 'star of david'], ['☸️', 'wheel of dharma'],
    ],
  },
  {
    key: 'flags',
    label: 'Flags',
    tabIcon: '🏳️',
    items: [
      ['🏳️', 'white flag'], ['🏴', 'black flag'], ['🏁', 'chequered flag finish race'],
      ['🚩', 'triangular flag'], ['🏳️‍🌈', 'rainbow flag pride'], ['🏳️‍⚧️', 'transgender flag'],
      ['🏴‍☠️', 'pirate flag'], ['🇬🇧', 'united kingdom uk britain gb'], ['🇵🇱', 'poland polish pl'],
      ['🇺🇸', 'united states usa america us'], ['🇦🇺', 'australia au'], ['🇻🇳', 'vietnam vn'],
      ['🇮🇪', 'ireland ie'], ['🇫🇷', 'france french fr'], ['🇩🇪', 'germany german de'],
      ['🇪🇸', 'spain spanish es'], ['🇮🇹', 'italy italian it'], ['🇵🇹', 'portugal pt'],
      ['🇳🇱', 'netherlands dutch nl'], ['🇧🇪', 'belgium be'], ['🇨🇭', 'switzerland ch'],
      ['🇦🇹', 'austria at'], ['🇸🇪', 'sweden se'], ['🇳🇴', 'norway no'],
      ['🇩🇰', 'denmark dk'], ['🇫🇮', 'finland fi'], ['🇮🇸', 'iceland is'],
      ['🇨🇿', 'czechia czech cz'], ['🇸🇰', 'slovakia sk'], ['🇭🇺', 'hungary hu'],
      ['🇷🇴', 'romania ro'], ['🇧🇬', 'bulgaria bg'], ['🇬🇷', 'greece gr'],
      ['🇭🇷', 'croatia hr'], ['🇸🇮', 'slovenia si'], ['🇺🇦', 'ukraine ua'],
      ['🇱🇹', 'lithuania lt'], ['🇱🇻', 'latvia lv'], ['🇪🇪', 'estonia ee'],
      ['🇹🇷', 'turkey tr'], ['🇨🇦', 'canada ca'], ['🇲🇽', 'mexico mx'],
      ['🇧🇷', 'brazil br'], ['🇦🇷', 'argentina ar'], ['🇨🇱', 'chile cl'],
      ['🇨🇴', 'colombia co'], ['🇵🇪', 'peru pe'], ['🇯🇵', 'japan japanese jp'],
      ['🇰🇷', 'south korea kr'], ['🇨🇳', 'china chinese cn'], ['🇹🇼', 'taiwan tw'],
      ['🇭🇰', 'hong kong hk'], ['🇸🇬', 'singapore sg'], ['🇹🇭', 'thailand th'],
      ['🇲🇾', 'malaysia my'], ['🇮🇩', 'indonesia id'], ['🇵🇭', 'philippines ph'],
      ['🇮🇳', 'india in'], ['🇵🇰', 'pakistan pk'], ['🇧🇩', 'bangladesh bd'],
      ['🇳🇿', 'new zealand nz'], ['🇿🇦', 'south africa za'], ['🇪🇬', 'egypt eg'],
      ['🇳🇬', 'nigeria ng'], ['🇰🇪', 'kenya ke'], ['🇲🇦', 'morocco ma'],
      ['🇦🇪', 'united arab emirates uae ae'], ['🇸🇦', 'saudi arabia sa'], ['🇮🇱', 'israel il'],
      ['🇷🇺', 'russia ru'], ['🇪🇺', 'european union eu'],
    ],
  },
];

/** Flat [glyph, keywords] list — used by the picker's search. */
export const ALL_EMOJI = EMOJI_GROUPS.flatMap((g) => g.items);
