-- server/migrations/013_encryption_drop_plaintext.sql
-- Phase 9.5 step 3 of 3.  ***IRREVERSIBLE. THIS DESTROYS DATA.***
--
-- Written 2026-08-18 to REPLACE the draft that lived in
-- docs/superpowers/plans/2026-07-17-phase9-pln-privacy-history-pace-special.md.
-- That draft must never be run. It was written in July against the ORIGINAL
-- scope and drops five columns whose `_enc` twins do not exist, because the
-- 2026-08-09 re-scope removed them from migration 012:
--
--     transactions.description        -> description_enc        NEVER CREATED
--     categories.name                 -> name_enc               NEVER CREATED
--     savings_goals.name              -> name_enc               NEVER CREATED
--     savings_contributions.note      -> note_enc               NEVER CREATED
--     subscription_overrides.display_name -> display_name_enc   NEVER CREATED
--
-- Pasted into the SQL editor, its `drop column description` succeeds and its
-- `rename column description_enc to description` then fails on a column that was
-- never added. Depending on whether the editor wraps the batch in a transaction,
-- that is the permanent loss of every transaction description, category name,
-- goal name, contribution note and subscription label in the database.
--
-- ============================ DO NOT RUN THIS YET ============================
-- Preconditions, ALL of them, in this order:
--
--   1. Migrations 012 AND 018 applied.
--   2. `DATA_ENCRYPTION_KEY` generated by Alex, set in server/.env AND in Vercel,
--      and backed up in TWO places offline. After this migration the key is the
--      ONLY way to read anyone's financial data. See SECURITY.md.
--   3. The route sweep deployed and running in dual-write mode for long enough
--      that every write path has demonstrably written both columns.
--   4. `node scripts/encrypt-backfill.mjs` run to completion.
--   5. `node scripts/verify-encryption.mjs` EXITS 0. Its exit code is the only
--      thing that authorises this file. A UI click-through is not evidence.
--   6. A fresh database backup taken AFTER step 5 and BEFORE this file.
--   7. The app paused or read-only, and the nightly recurrences cron disabled,
--      for the whole window from step 5 to the end of this file. `vercel.json`
--      schedules /api/cron/recurrences at 03:00 — it INSERTS transactions, and a
--      row it writes between the gate passing and this migration running would be
--      dropped un-encrypted.
--   8. Re-run step 5 immediately before this file, in the same window.
--
-- NO RENAMES. The July draft renamed `<col>_enc` over the dropped plaintext
-- column. That is what made the cutover unsafe: the rename turns a `numeric`
-- column into `text`, so any still-running old server instance — or the cron —
-- writes a bare number into the column the new code reads as ciphertext, and
-- that row never decrypts again. Keeping the `_enc` suffix forever costs nothing
-- but a slightly uglier column name, and it means this file is the ONLY
-- irreversible step in the whole rollout.
-- =============================================================================

begin;

-- The FX constraints reference original_amount, which is about to go. Replace
-- them BEFORE the drop so the invariant is never unenforced.
alter table public.transactions
  drop constraint if exists transactions_fx_all_or_nothing;
alter table public.transactions
  drop constraint if exists transactions_fx_sane;

alter table public.transactions
  drop column if exists amount,
  drop column if exists original_amount,
  drop column if exists description;

alter table public.budgets
  drop column if exists amount_limit;

alter table public.savings_goals
  drop column if exists target_amount,
  drop column if exists current_amount,
  drop column if exists name;

alter table public.savings_contributions
  drop column if exists amount,
  drop column if exists note;

alter table public.user_stats
  drop column if exists monthly_limit;

alter table public.ask_messages
  drop column if exists content;

alter table public.recurrences
  drop column if exists amount,
  drop column if exists description;

alter table public.special_groups
  drop column if exists name;

-- subscription_overrides needs its PRIMARY KEY moved before the plaintext
-- merchant_key can go. The unique index created by migration 018 is what makes
-- this safe: if two merchant keys had collided under one user, that index would
-- already have refused to build.
alter table public.subscription_overrides
  drop constraint if exists subscription_overrides_pkey;

alter table public.subscription_overrides
  add constraint subscription_overrides_pkey primary key (user_id, merchant_key_hmac);

alter table public.subscription_overrides
  drop column if exists merchant_key,
  drop column if exists display_name;

-- Re-state the all-or-nothing FX invariant over the ciphertext column. Same
-- meaning as migration 016's version, expressed against original_amount_enc.
alter table public.transactions
  add constraint transactions_fx_all_or_nothing check (
    (original_amount_enc is null and original_currency is null and fx_rate is null)
    or (original_amount_enc is not null and original_currency is not null and fx_rate is not null)
  );

-- What is still enforceable once the amount is ciphertext. The dropped half —
-- `original_amount > 0` — CANNOT be expressed against a ciphertext and now lives
-- only in the Zod schema at the API boundary. routes/transactions.js is the sole
-- writer of these columns; if that validation is ever removed, this constraint
-- does not catch it.
alter table public.transactions
  add constraint transactions_fx_sane check (
    (original_currency is null or original_currency ~ '^[A-Z]{3}$')
    and (fx_rate is null or fx_rate > 0)
  );

commit;

-- After this file: set ENCRYPTION_PHASE=enc in Vercel and redeploy, so the routes
-- stop trying to write columns that no longer exist.
