-- server/migrations/019_encryption_drop_plaintext.sql
-- Phase 9.5 step 3 of 3.
--
-- RENUMBERED 013 -> 019 on 2026-08-18 (Codex stage-4 VERIFY). As 013 it sorted
-- BEFORE 018, so anyone applying migrations in filename order — the obvious and
-- correct instinct — would have dropped the plaintext columns before 018 had
-- created the ciphertext columns to replace them. The file said "run me last" in
-- prose; the filename said the opposite, and the filename is what a tired person
-- follows at 3am. Order is now: 012, 018, backfill, gate, 019.  ***IRREVERSIBLE. THIS DESTROYS DATA.***
--
-- Written 2026-08-18 to REPLACE the draft that lived in
-- docs/superpowers/plans/2026-07-17-phase9-pln-privacy-history-pace-special.md.
-- That draft must never be run. It was written in July against the ORIGINAL
-- scope and drops five columns whose `_enc` twins do not exist, because the
-- 2026-08-09 re-scope removed them from migration 012:
--
--     transactions.description        -> description_enc        NEVER CREATED
--     categories.name                 -> name_enc               NEVER CREATED
--     savings_goals.name              -> name_enc               NEVER CREATED
--     savings_contributions.note      -> note_enc               NEVER CREATED
--     subscription_overrides.display_name -> display_name_enc   NEVER CREATED
--
-- Pasted into the SQL editor, its `drop column description` succeeds and its
-- `rename column description_enc to description` then fails on a column that was
-- never added. Depending on whether the editor wraps the batch in a transaction,
-- that is the permanent loss of every transaction description, category name,
-- goal name, contribution note and subscription label in the database.
--
-- ============================ DO NOT RUN THIS YET ============================
-- Preconditions, ALL of them, in this order:
--
--   1. Migrations 012, 018 AND 018a applied (in that order, all before this file).
--   2. `DATA_ENCRYPTION_KEY` generated by Alex, set in server/.env AND in Vercel,
--      and backed up in TWO places offline. After this migration the key is the
--      ONLY way to read anyone's financial data. See SECURITY.md.
--   3. The route sweep deployed and running in dual-write mode for long enough
--      that every write path has demonstrably written both columns.
--   4. `node scripts/encrypt-backfill.mjs` run to completion.
--   5. `node scripts/verify-encryption.mjs` EXITS 0. Its exit code is the only
--      thing that authorises this file. A UI click-through is not evidence.
--   6. A fresh database backup taken AFTER step 5 and BEFORE this file.
--   7. The migration-018a WRITE BARRIER ENGAGED for the whole window from step 5
--      to the end of this file, and the nightly recurrences cron disabled:
--          update public.encryption_cutover set engaged = true, engaged_at = now();
--      `vercel.json` schedules /api/cron/recurrences at 03:00 — it INSERTS
--      transactions and cannot write `_enc`, so a row it writes between the gate
--      passing and this migration running would be dropped un-encrypted.
--      "Pause the app" used to be an instruction nobody could verify. It is now
--      enforced by the database and CHECKED by the gate, because Codex proved a
--      write landing inside an already-scanned page is invisible to any number of
--      read passes. [stage-4 RE-VERIFY finding 2]
--   8. Re-run step 5 immediately before this file, in the same window.
--   9. AFTER this file commits, and not before, release the barrier:
--          update public.encryption_cutover set engaged = false, engaged_at = null;
--      then set ENCRYPTION_PHASE=enc in Vercel, redeploy, and re-enable the cron.
--
-- NO RENAMES. The July draft renamed `<col>_enc` over the dropped plaintext
-- column. That is what made the cutover unsafe: the rename turns a `numeric`
-- column into `text`, so any still-running old server instance — or the cron —
-- writes a bare number into the column the new code reads as ciphertext, and
-- that row never decrypts again. Keeping the `_enc` suffix forever costs nothing
-- but a slightly uglier column name, and it means this file is the ONLY
-- irreversible step in the whole rollout.
-- =============================================================================

begin;

-- --- the signup trigger must stop writing categories.name FIRST --------------
--
-- migration 001 lines 158-192 define handle_new_user() as an AFTER INSERT trigger
-- on auth.users that does a literal
--     insert into public.categories (user_id, name, icon, color, type, ...)
-- for the twelve defaults. Dropping categories.name below without replacing this
-- function first means the next signup raises inside the trigger, and because the
-- trigger fires on auth.users that rolls the whole signup back: NOBODY CAN CREATE
-- AN ACCOUNT AGAIN, with nothing in the app's own logs to explain it.
--
-- The seeding cannot stay in the database, because the database has no
-- DATA_ENCRYPTION_KEY and therefore cannot write name_enc/name_hmac. It moves to
-- the API, exactly as the encryption spec and BUILD_PLAN.md always required:
-- lib/defaultCategories.js, called from GET /api/me, idempotent, already live and
-- already a no-op while this trigger still seeds. Migration 018 adds the partial
-- unique index that keeps it atomic.
--
-- user_stats seeding STAYS here: it writes no encrypted column, and GET /api/me
-- has its own fallback insert for it.
-- [Codex stage-4 RE-VERIFY finding 5, 2026-08-18]

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_stats (user_id)
  values (new.id)
  on conflict (user_id) do nothing;

  -- Default categories are seeded by the API (lib/defaultCategories.js, called
  -- from GET /api/me). They are not seeded here because this function cannot
  -- encrypt, and after this migration categories.name does not exist.

  return new;
end;
$$;

-- Migration 009 keeps trigger-only definer functions off the exposed RPC surface.
-- CREATE OR REPLACE preserves privileges, but re-stating it costs nothing and
-- means this file is correct even if 009 was never applied.
revoke execute on function public.handle_new_user() from anon, authenticated, public;

-- The FX constraints reference original_amount, which is about to go. Replace
-- them BEFORE the drop so the invariant is never unenforced.
alter table public.transactions
  drop constraint if exists transactions_fx_all_or_nothing;
alter table public.transactions
  drop constraint if exists transactions_fx_sane;

alter table public.transactions
  drop column if exists amount,
  drop column if exists original_amount,
  drop column if exists description;

alter table public.budgets
  drop column if exists amount_limit;

alter table public.savings_goals
  drop column if exists target_amount,
  drop column if exists current_amount,
  drop column if exists name;

alter table public.savings_contributions
  drop column if exists amount,
  drop column if exists note;

alter table public.user_stats
  drop column if exists monthly_limit;

alter table public.ask_messages
  drop column if exists content;

alter table public.recurrences
  drop column if exists amount,
  drop column if exists description;

alter table public.categories
  drop column if exists name;

alter table public.special_groups
  drop column if exists name;

-- subscription_overrides needs its PRIMARY KEY moved before the plaintext
-- merchant_key can go. The unique index created by migration 018 is what makes
-- this safe: if two merchant keys had collided under one user, that index would
-- already have refused to build.
alter table public.subscription_overrides
  drop constraint if exists subscription_overrides_pkey;

alter table public.subscription_overrides
  add constraint subscription_overrides_pkey primary key (user_id, merchant_key_hmac);

alter table public.subscription_overrides
  drop column if exists merchant_key,
  drop column if exists display_name;

-- Re-state the all-or-nothing FX invariant over the ciphertext column. Same
-- meaning as migration 016's version, expressed against original_amount_enc.
alter table public.transactions
  add constraint transactions_fx_all_or_nothing check (
    (original_amount_enc is null and original_currency is null and fx_rate is null)
    or (original_amount_enc is not null and original_currency is not null and fx_rate is not null)
  );

-- What is still enforceable once the amount is ciphertext. The dropped half —
-- `original_amount > 0` — CANNOT be expressed against a ciphertext and now lives
-- only in the Zod schema at the API boundary. routes/transactions.js is the sole
-- writer of these columns; if that validation is ever removed, this constraint
-- does not catch it.
alter table public.transactions
  add constraint transactions_fx_sane check (
    (original_currency is null or original_currency ~ '^[A-Z]{3}$')
    and (fx_rate is null or fx_rate > 0)
  );

-- --- restore the invariants the dropped columns carried ---------------------
--
-- Every column dropped above was created by migration 012/018 as a NULLABLE text
-- column, because the backfill has to write them one row at a time. Once the
-- plaintext is gone, the database stops guaranteeing that a transaction has an
-- amount, that a category has a name, or that a subscription has a key — unless
-- the invariant is re-applied here. Derived from `notNull` in
-- lib/encryptedFields.js and asserted by test/encryptionScope.test.js.
-- [Codex stage-4 VERIFY, 2026-08-18]
--
-- If any of these fails with "column contains null values", the backfill did NOT
-- complete and the gate should never have passed. STOP and restore the backup.

alter table public.transactions      alter column amount_enc         set not null;
alter table public.budgets           alter column amount_limit_enc   set not null;
alter table public.savings_goals     alter column target_amount_enc  set not null;
alter table public.savings_goals     alter column current_amount_enc set not null;
alter table public.savings_goals     alter column name_enc           set not null;
alter table public.savings_contributions alter column amount_enc     set not null;
alter table public.ask_messages      alter column content_enc        set not null;
alter table public.recurrences       alter column amount_enc         set not null;
alter table public.special_groups    alter column name_enc           set not null;
alter table public.categories        alter column name_enc           set not null;
alter table public.categories        alter column name_hmac          set not null;
alter table public.subscription_overrides alter column merchant_key_enc  set not null;
alter table public.subscription_overrides alter column merchant_key_hmac set not null;

-- Deliberately still nullable, because their plaintext originals were:
--   transactions.original_amount_enc, transactions.description_enc,
--   recurrences.description_enc, savings_contributions.note_enc,
--   subscription_overrides.display_name_enc, user_stats.monthly_limit_enc.

-- --- what the database can NO LONGER enforce ---------------------------------
--
-- These CHECK constraints died with their columns and CANNOT be expressed against
-- a ciphertext. They now live ONLY in the Zod schemas at the API boundary, and
-- nothing in the database will catch it if that validation is ever weakened:
--
--   transactions.amount           > 0
--   budgets.amount_limit          > 0
--   savings_goals.target_amount   > 0
--   savings_contributions.amount  > 0
--   recurrences.amount            > 0
--   transactions.original_amount  > 0
--   ask_messages.content          char_length between 1 and 8000
--
-- This is an unavoidable consequence of encrypting the values, not an oversight.
-- It is the strongest argument for keeping the API-boundary validation tested.

commit;

-- After this file: set ENCRYPTION_PHASE=enc in Vercel and redeploy, so the routes
-- stop trying to write columns that no longer exist.
